### ISSUE TITLE
is test coverage sufficient?

### ISSUE THREAD

**Issue by barmintor** [samvera/rubydora#114]
A requirement for being in the Samvera organization is: Good unit test coverage measured by community (e.g. 100% or 75% of what’s important)

As this hasn't been defined, we in the Core Component Maintenance Working Group would like to ask the product owner if you or any developers who work on this project know if they feel like the coverage is sufficient on this project to be confident in continuing work on it? If not, we encourage you to create an issue to increase test coverage and add the maintenance label. If so, please close this issue.

Thanks!

**Comment by tpendragon** [comment]
The project is currently at 99%, which seems likely to be sufficient. If the product owner (@jcoyne) feels like it would be useful for us to try to get it higher please make a ticket with the maintenance label.
